version: '3.8'
services:
  backend:
    build: ./backend
    env_file: .env.production
    ports:
      - '4000:4000'
    depends_on:
      - db
    restart: unless-stopped
  frontend:
    build: ./frontend
    ports:
      - '80:80'
    depends_on:
      - backend
    restart: unless-stopped
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: servidumbres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
  minio:
    image: minio/minio
    command: server /data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - '9000:9000'
    volumes:
      - minio-data:/data
volumes:
  db-data:
  minio-data:
