services:
  - type: web
    name: servidumbres-grenergy
    env: node
    branch: main
    rootDir: backend
    buildCommand: npm install && cd ../frontend && npm install && npm run build && cp -r dist ../backend/public || cp -r dist ./public
    startCommand: node index.js
    plan: free
